name: Build Downstream Projects

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'NVIDIA/sphinx-llm'
    strategy:
      matrix:
        python-version: ["3.12"]
        downstream-project:
          - repo: nolar/kopf
            install_command: "uv pip install --group docs -e ."
            build_command: "sphinx-build docs/ docs/_build/ -b html"
          - repo: kr8s-org/kr8s
            install_command: "uv sync --dev"
            build_command: "uv run --dev sphinx-build docs/ docs/_build/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout Downstream Project
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.downstream-project.repo }}
          path: ${{ matrix.downstream-project.repo }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"

      - name: Install Downstream Project
        run: |
          cd ${{ matrix.downstream-project.repo }}
          ${{ matrix.downstream-project.install_command }}

      - name: Install sphinx-llm
        run: |
          uv pip install -e .

      - name: Build Downstream Project
        id: build-downstream-project
        run: |
          cd ${{ matrix.downstream-project.repo }}
          ${{ matrix.downstream-project.build_command }}

      - name: Check for llms.txt build files
        run: |
          found=$(find ${{ matrix.downstream-project.repo }} \( -name "llms.txt" -o -name "llms-full.txt" -o -name "*.html.md" \))
          if [ -z "$found" ]; then
            echo "No build files found"
            exit 1
          fi
          echo "Build files found:"
          echo "$found"

      - name: Open issue if build fails
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Downstream build failed for ${process.env.GITHUB_SHA.substring(0, 8)}: ${{ matrix.downstream-project.repo }}`,
              body: `Downstream testing failed, see ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });
